### PR TITLE
Create wrapper to agda-mode aswell

### PR DESCRIPTION
**Pull request by grahnen**
I'm quite new to nix/NixOS, so sorry if I'm doing this the wrong way.

If we want the agda-mode binary to be available for emacs (as it is with previous agda versions from nix), we need to add a link to it in "agdaWithPackages".

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by alexarice** [comment]
This looks like it will overwrite the agda executable with agda-mode. Perhaps I am reading it wrong.

To be honest I have no idea how emacs usually finds the agda-mode executable as I use the nixpkgs `emacsPackages.agda2-mode` package

**Comment by grahnen** [comment]
I was indeed overwriting it, changed it to write the correct file.

The way Agda is usually found by emacs is through invoking the shell command "agda-mode locate" from emacs.

From my config file:
```
(load-file (let ((coding-system-for-read 'utf-8))
                  (shell-command-to-string "agda-mode locate")))

(add-to-list 'exec-path (let ((coding-system-for-read 'utf-8))
                            (file-name-directory (shell-command-to-string "which agda"))))
```

**Comment by alexarice** [comment]
This seems reasonable to me, I'll give it a test

**Comment by alexarice** [comment]
Have added this to the pr, thanks :)

**Pull request closed without merging**
